sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 6
  - 8
  - 10
matrix:
  fast_finish: true
script: npm run travis
before_install:
  - npm i -g npm
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
